import type { AuthNS } from '../types';

const auth: AuthNS = {
  login: {
    tagline: 'Private security on‑demand', title: 'Sign in', subtitle: 'Access your secure space',
    email_label: 'Email address', email_placeholder: 'you@example.com',
    password_label: 'Password', password_placeholder: '••••••••',
    submit: 'Sign in', submitting: 'Signing in…',
    secure_text: 'TLS encrypted connection · GDPR compliant',
    no_account: 'No account yet?', create_link: 'Create account', biometrics: 'Biometrics',
    errors: { email_required: 'Email is required', email_invalid: 'Invalid email address', password_required: 'Password is required', invalid_creds: 'Incorrect email or password.', generic: 'Sign-in failed' },
    alert: { title: 'Unable to sign in' },
  },
  register: {
    title: 'Create account', subtitle: 'Join Provalk in seconds',
    perks: { verified: 'Verified & insured agents', quote: 'Instant online quote', payment: '100% secure payment' },
    email_label: 'Email address', email_placeholder: 'you@example.com',
    account_type: 'ACCOUNT TYPE', individual: 'Individual', individual_sub: 'Personal use', company: 'Business', company_sub: 'B2B invoicing',
    full_name_label: 'Full name', full_name_placeholder: 'John Smith',
    phone_label: 'Phone (optional)', phone_placeholder: '+1 555 000 0000',
    password_hint: 'Letters, numbers and special characters recommended', password_placeholder: '8 characters minimum',
    submit: 'Create my account', rgpd: 'By creating an account you agree to our Terms & Conditions and Privacy Policy. Your data is protected in accordance with GDPR.',
    company_name_label: 'Company name', company_name_placeholder: 'E.g. ACME LLC',
    siret_label: 'SIRET', siret_hint: '14-digit INSEE registration number',
    accept_terms: 'I accept the Terms of Service and Privacy Policy (GDPR).',
    strength: { weak: 'Weak', fair: 'Fair', good: 'Good', strong: 'Strong' },
    has_account: 'Already registered?', login_link: 'Sign in',
    errors: { full_name_required: 'Full name is required', email_required: 'Email is required', email_invalid: 'Invalid email address', password_length: '8 characters minimum', password_complexity: 'Must contain an uppercase letter and a digit', phone_invalid: 'Invalid phone number', company_name_required: 'Company name is required', siret_invalid: 'Invalid SIRET (14 digits required)', terms_required: 'You must accept the Terms to continue', email_taken: 'This email is already in use', too_many_attempts: 'Too many attempts. Try again in 1 minute.', network: 'Connection failed — check your network', generic: 'Error while creating account' },
    alert: { title: 'Unable to register' },
  },
  onboarding: {
    next: 'Next', skip: 'Skip', get_started: 'Get started',
    slides: {
      security_title: 'Premium security\non demand',
      security_subtitle: 'Book qualified and certified security agents for your events, sites or establishments.',
      tracking_title: 'Real-time\ntracking',
      tracking_subtitle: 'Locate your agents on the map, track check-ins and receive instant alerts.',
      payment_title: 'Simple &\nsecure payment',
      payment_subtitle: 'Pay by card or SEPA transfer. Download your invoices in one tap.',
    },
  },
  two_fa: {
    title: 'Two-Factor Authentication', description: 'Enter the 6-digit code from your authenticator app.',
    placeholder: '000000', submit: 'Verify', submitting: 'Verifying…', invalid: 'Invalid code. Please try again.',
  },
  two_fa_screen: {
    header: 'Verification', title: 'Verification code',
    subtitle: 'Enter the 6-digit code sent to your phone or generated by your 2FA app.',
    verify: 'Verify', incomplete_title: 'Incomplete code', incomplete_body: 'Enter all 6 digits.',
    invalid_title: 'Invalid code', invalid_body: 'The code is incorrect or expired.',
    resend: 'Resend code', resent_title: 'Code resent', resent_body: 'A new code has been sent.', resend_error: 'Unable to resend code.',
  },
};

export default auth;
