/**
 * LeafletMapView — [FIX H3] shared WebView shell for every Leaflet-based map
 * in this app (LiveTrackingScreen, MissionMapView, AgentApproachBanner,
 * MapLocationPicker).
 *
 * WHY THIS EXISTS:
 *  Each of the four screens previously embedded its own full HTML document,
 *  fetching Leaflet's JS/CSS from https://unpkg.com/leaflet@1.9.4/... at
 *  WebView load time. On a marginal connection — exactly the security-site
 *  context this app is used in — that fetch can stall, and the map silently
 *  never initialises (the 'ready' postMessage never fires). Only one of the
 *  four screens (MissionMapView) had a real error/retry state; the other
 *  three left the user looking at a blank/dark box with no explanation.
 *
 *  This component fixes both problems at once:
 *   1. Leaflet's JS/CSS are inlined from LEAFLET_JS/LEAFLET_CSS (generated by
 *      scripts/generate-leaflet-bundle.js from the installed npm package) —
 *      no CDN round-trip, the map engine itself ships inside the JS bundle.
 *   2. A single, consistent loading/error/retry UI, modelled on the one
 *      MissionMapView already had, so all four screens get it for free.
 *
 *  OSM tile imagery is NOT inlined — only the ~160KB Leaflet engine is.
 *  Tiles still come from config.maps.tileUrlTemplate over the network; that
 *  fetch is per-tile and naturally degrades (partial map) rather than
 *  failing all-or-nothing the way the old CDN script tag did.
 *
 * USAGE:
 *  Each caller supplies only the inner Leaflet JS for ITS map (markers,
 *  geofence circles, drag handlers, etc.) via `bodyScript` — a function body
 *  string that runs inside the WebView once Leaflet + the DOM are ready, with
 *  `L` and a `map` instance already constructed. The caller is responsible
 *  for calling `signalReady()` (injected automatically) once its own setup
 *  is done, and for defining any `window.xxx` bridge functions it wants to
 *  call later via `injectJavaScript`.
 *
 *  This deliberately does NOT try to unify the four screens' very different
 *  interaction models (tap-to-place vs. live-tracking vs. read-only pin vs.
 *  mini route-preview) into one generic API — that would either bloat this
 *  component or leak abstraction. It only unifies the two things that were
 *  genuinely duplicated and fragile: the CDN load and the error/retry UI.
 */
import React, {
  useRef, useState, useCallback, useMemo, useImperativeHandle, forwardRef,
} from 'react';
import {
  View, Text, StyleSheet, ActivityIndicator,
  Animated, TouchableOpacity,
} from 'react-native';
import { WebView } from 'react-native-webview';
import type { WebView as WebViewType } from 'react-native-webview';
import { RefreshCw, WifiOff } from 'lucide-react-native';
import i18n from '@i18n';
import { colors } from '@theme/colors';
import { spacing, radius } from '@theme/spacing';
import { fontSize, fontFamily } from '@theme/typography';
import { LEAFLET_JS, LEAFLET_CSS } from '@assets/leaflet/leaflet.inline';

export interface LeafletMapViewHandle {
  /** Run injectJavaScript against the underlying WebView once it's ready. */
  inject: (js: string) => void;
  /** Force a reload (remounts the WebView), e.g. from a parent retry action. */
  reload: () => void;
}

export interface LeafletMapViewProps {
  /**
   * Extra <style> rules specific to this map (marker classes, animations…).
   * Merged after the shared base styles so callers can override them.
   */
  extraStyle?: string;
  /**
   * The body of an IIFE that runs once Leaflet is loaded. Has `L` and a
   * ready-made `map` variable in scope (already instantiated with the given
   * initial view). Must call `signalReady()` when initial setup is complete
   * — this is what flips the shell from "loading" to showing the map, and
   * is also what the screen's own onMessage 'ready' handling (if it has any
   * additional logic) should key off of, since this shell intercepts and
   * forwards ALL postMessage payloads to `onMessage`.
   */
  bodyScript: string;
  /** Initial map center. */
  centerLat: number;
  centerLng: number;
  initialZoom?: number;
  /** Map-level interaction flags forwarded into the underlying L.map() call. */
  zoomControl?: boolean;
  dragging?: boolean;
  /** Forwarded verbatim — parent screens use this for their own message types. */
  onMessage?: (event: any) => void;
  /** Fires once when the map signals 'ready' (after signalReady() in bodyScript). */
  onReady?: () => void;
  /** Fires when the WebView fails to load or errors. */
  onMapError?: () => void;
  /** Fixed height; omit to fill the parent (absolute fill). */
  height?: number;
  /** Hides the built-in loading/error chrome — caller renders its own. */
  hideChrome?: boolean;
  style?: any;
}

/**
 * Builds the full HTML document. Leaflet JS/CSS are inlined directly (no
 * <link>/<script src> pointing at a CDN) — see file header.
 */
function buildHTML(props: {
  centerLat: number;
  centerLng: number;
  initialZoom: number;
  zoomControl: boolean;
  dragging: boolean;
  extraStyle: string;
  bodyScript: string;
}): string {
  const {
    centerLat, centerLng, initialZoom, zoomControl, dragging, extraStyle, bodyScript,
  } = props;

  return `<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
<style>${LEAFLET_CSS}</style>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  html, body, #map { width:100%; height:100%; background:#0a0c0f; }
  .leaflet-control-attribution { display:none !important; }
  .leaflet-control-zoom a {
    background:#0c1220 !important; color:#bc933b !important;
    border-color:#1e2d45 !important;
  }
  ${extraStyle}
</style>
</head>
<body>
<div id="map"></div>
<script>${LEAFLET_JS}</script>
<script>
(function() {
  function send(type, extra) {
    var msg = Object.assign({ type: type }, extra || {});
    if (window.ReactNativeWebView) {
      window.ReactNativeWebView.postMessage(JSON.stringify(msg));
    }
  }
  // Exposed to the caller's bodyScript so it can signal "initial setup done".
  // Distinct from raw postMessage so every screen's ready-handling is uniform.
  function signalReady() { send('ready'); }

  var map = L.map('map', {
    zoomControl: ${zoomControl},
    dragging: ${dragging},
  }).setView([${centerLat}, ${centerLng}], ${initialZoom});

  map.on('dragstart', function() { send('pan'); });

  // ── Caller-supplied body ──────────────────────────────────────────────
  ${bodyScript}
  // ── End caller-supplied body ─────────────────────────────────────────
})();
</script>
</body>
</html>`;
}

export const LeafletMapView = forwardRef<LeafletMapViewHandle, LeafletMapViewProps>(
  function LeafletMapView(
    {
      extraStyle = '',
      bodyScript,
      centerLat,
      centerLng,
      initialZoom = 14,
      zoomControl = true,
      dragging = true,
      onMessage,
      onReady,
      onMapError,
      height,
      hideChrome = false,
      style,
    },
    ref,
  ) {
    const webRef = useRef<WebViewType>(null);
    const jsReadyRef = useRef(false);
    const fadeAnim = useRef(new Animated.Value(0)).current;

    const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading');
    // Increment to force a full WebView remount on retry (a stalled CDN/script
    // load can leave the WebView in a state that onError never reliably fires
    // for; remounting is the one approach guaranteed to retry from scratch).
    const [retryKey, setRetryKey] = useState(0);

    const html = useMemo(
      () => buildHTML({
        centerLat, centerLng, initialZoom, zoomControl, dragging, extraStyle, bodyScript,
      }),
      // eslint-disable-next-line react-hooks/exhaustive-deps
      [centerLat, centerLng, initialZoom, zoomControl, dragging, extraStyle, bodyScript, retryKey],
    );

    const inject = useCallback((js: string) => {
      if (!webRef.current || !jsReadyRef.current) return;
      webRef.current.injectJavaScript(`(function(){${js}})(); true;`);
    }, []);

    const reload = useCallback(() => {
      jsReadyRef.current = false;
      fadeAnim.setValue(0);
      setStatus('loading');
      setRetryKey((k) => k + 1);
    }, [fadeAnim]);

    useImperativeHandle(ref, () => ({ inject, reload }), [inject, reload]);

    const handleMessage = useCallback((event: any) => {
      try {
        const msg = JSON.parse(event.nativeEvent.data);
        if (msg.type === 'ready') {
          jsReadyRef.current = true;
          setStatus('ready');
          Animated.timing(fadeAnim, { toValue: 1, duration: 350, useNativeDriver: true }).start();
          onReady?.();
        }
      } catch { /* ignore parse errors, still forward below */ }
      onMessage?.(event);
    }, [fadeAnim, onMessage, onReady]);

    const handleError = useCallback(() => {
      setStatus('error');
      onMapError?.();
    }, [onMapError]);

    const containerStyle = height != null ? { height } : StyleSheet.absoluteFillObject;

    return (
      <View style={[styles.container, containerStyle, style]}>
        {!hideChrome && status === 'loading' && (
          <View style={styles.overlay}>
            <ActivityIndicator color={colors.primary} size="small" />
            <Text style={styles.overlayText}>{i18n.t('common:map_loading')}</Text>
          </View>
        )}

        {!hideChrome && status === 'error' && (
          <View style={styles.overlay}>
            <WifiOff size={28} color={colors.textMuted} strokeWidth={1.5} />
            <Text style={styles.errorTitle}>{i18n.t('common:map_unavailable')}</Text>
            <Text style={styles.errorSub}>{i18n.t('common:check_connection')}</Text>
            <TouchableOpacity style={styles.retryBtn} onPress={reload} activeOpacity={0.8}>
              <RefreshCw size={13} color={colors.primary} strokeWidth={2} />
              <Text style={styles.retryText}>{i18n.t('common:retry')}</Text>
            </TouchableOpacity>
          </View>
        )}

        <Animated.View style={[StyleSheet.absoluteFill, { opacity: hideChrome ? 1 : fadeAnim }]}>
          <WebView
            key={retryKey}
            ref={webRef}
            source={{ html }}
            style={styles.webview}
            onMessage={handleMessage}
            onError={handleError}
            onHttpError={handleError}
            javaScriptEnabled
            domStorageEnabled
            scrollEnabled={false}
            bounces={false}
            overScrollMode="never"
            originWhitelist={['*']}
            mixedContentMode="always"
            allowUniversalAccessFromFileURLs
            allowFileAccess
          />
        </Animated.View>
      </View>
    );
  },
);

const styles = StyleSheet.create({
  container: { position: 'relative', overflow: 'hidden' },
  webview: { flex: 1, backgroundColor: 'transparent' },

  overlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing[2],
    backgroundColor: colors.backgroundElevated,
    zIndex: 10,
    paddingHorizontal: spacing[5],
  },
  overlayText: { fontFamily: fontFamily.body, fontSize: fontSize.xs, color: colors.textMuted },
  errorTitle: {
    fontFamily: fontFamily.bodyMedium, fontSize: fontSize.sm,
    color: colors.textSecondary, marginTop: spacing[1],
  },
  errorSub: { fontFamily: fontFamily.body, fontSize: fontSize.xs, color: colors.textMuted },
  retryBtn: {
    flexDirection: 'row', alignItems: 'center', gap: spacing[1] + 2,
    marginTop: spacing[2], backgroundColor: colors.primarySurface,
    borderRadius: radius.full, paddingHorizontal: spacing[4], paddingVertical: spacing[2],
    borderWidth: 1, borderColor: colors.borderPrimary,
  },
  retryText: { fontFamily: fontFamily.bodyMedium, fontSize: fontSize.xs, color: colors.primary },
});
